export interface Trade {
    uid: string,
    id_card?: string,
    card_name: string,
    collection?: string,
    quality: string,
    trades_type: string,
    id_trades_type: string,
    id_trade_status: string,
    status: string,
    localization?: string,          // local da troca
    obs?: string
    id_buyer: string,
    buyer_name: string,
    buyer_status: string,
    buyer_id_status: string,
    security_postal_code_buyer?: string,
    id_seller: string,
    seller_name: string,
    seller_status: string,
    seller_id_status: string,
    security_postal_code_seller?: string,
    
}
export const initTrade: Trade = {
    uid: '',
    card_name: '',
    quality: '',
    trades_type: '',
    id_trades_type: '',
    id_trade_status: '',
    status: '',
    id_buyer: '',
    buyer_name: '',
    buyer_status: '',
    buyer_id_status: '',
    id_seller: '',
    seller_name: '',
    seller_status: '',
    seller_id_status: '',
};
